env: "dev"
storage_path: "storage/storage.db"
http_server:
  address: "localhost:8082"
db_host: "localhost"
db_port: "5432"
db_user: "root"
db_password: "724387"
db_name: "studentdb"
db_driver: "postgres"
